### PR TITLE
- Disable basic auth

### PR DESCRIPTION
**Pull request by ZaradarBH**
Disabling basic auth on traefik as it interferes with oauth middleware in the API's.

### CODE REVIEW

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |0|
| **Quality Gates** |OK|
| **Description** |Defaulting to Low Risk since all modified content is filtered away. This is either due to excluded content in your CodeScene settings, or because the change set only contains renames.|

**Comment by wcarlsen** [comment]
@kim-lindhard-dfds what do you say? It looks fine by me!

**Review by wcarlsen — DISMISSED** [review]
Looks good if Oauth has been tested and is in place where required.

**Comment by ZaradarBH** [comment]
I cant deploy the ADSync code to prod that will re-enable oauth before we enable proxy support for oauth or disable the basic filter.  :)

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |0|
| **Quality Gates** |OK|
| **Description** |Defaulting to Low Risk since all modified content is filtered away. This is either due to excluded content in your CodeScene settings, or because the change set only contains renames.|

**Review by SEQUOIIA — APPROVED** [review]
Looks swell to me.

**Pull request merged**
