### PR TITLE
Fix pipeline and docker

### PR DESCRIPTION
**Pull request by kim-lindhard-dfds**
Out of scope:
pipeline and docker file does many of the same tasks.

### CODE REVIEW

**Review by ZaradarBH — COMMENTED** [review]
By removing the WORKDIR command you are now running dotnet restore at the solution level, rather then restoring at the project level and letting nuget figure out which other dependencies to restore. Do we really want this behavior considering we are building an image for a single process (the WebApi) and not the entire solution?

**Review by ZaradarBH — COMMENTED** [review]
We can use docker-compose in place of this and discontinue the pipeline.sh setup all together, so why are we fixing this? :)

**Comment by kim-lindhard-dfds** [comment]
> We can use docker-compose in place of this and discontinue the pipeline.sh setup all together, so why are we fixing this? :)

I feel we should focus on making the existing work again instead of introducing more changes.
The build pipeline of the capability service is blocked because of the last round of changes we introduced: [Capability-Service-CI
](https://dfds.visualstudio.com/DevelopmentExcellence/_build?definitionId=901)

**Comment by kim-lindhard-dfds** [comment]
> By removing the WORKDIR command you are now running dotnet restore at the solution level, rather then restoring at the project level and letting nuget figure out which other dependencies to restore. Do we really want this behavior considering we are building an image for a single process (the WebApi) and not the entire solution?

Have a look at the path of the Dockerfile `src/CapabilityService.WebApi/Dockerfile`.
I read line 8 to 14 as following:
copy everything in the project folder src/CapabilityService.WebApi/
do a dotnet restore on the project CapabilityService.WebApi

**Comment by ZaradarBH** [comment]
> > By removing the WORKDIR command you are now running dotnet restore at the solution level, rather then restoring at the project level and letting nuget figure out which other dependencies to restore. Do we really want this behavior considering we are building an image for a single process (the WebApi) and not the entire solution?
> 
> Have a look at the path of the Dockerfile `src/CapabilityService.WebApi/Dockerfile`.
> I read line 8 to 14 as following:
> copy everything in the project folder src/CapabilityService.WebApi/
> do a dotnet restore on the project CapabilityService.WebApi

Read the docker compose. We copy everything from the root folder ander do this:

#Copy files to container file system.
COPY . . 

If we dont move to the project folder our restore is performed from the root of the repo.

**Comment by ZaradarBH** [comment]
> > We can use docker-compose in place of this and discontinue the pipeline.sh setup all together, so why are we fixing this? :)
> 
> I feel we should focus on making the existing work again instead of introducing more changes.
> The build pipeline of the capability service is blocked because of the last round of changes we introduced: [Capability-Service-CI ](https://dfds.visualstudio.com/DevelopmentExcellence/_build?definitionId=901)

So when it doesnt work on my machine because I have no native support for shell scripts? Then what? Is it not broken? :) Either you want to support windows development and make your code base "cross-platform" enabled or I might as well move back to working on Linux @ DFDS.

**Review by ZaradarBH — APPROVED** [review]

**Pull request merged**
