### PR TITLE
Feature/oauth enable

### PR DESCRIPTION
**Pull request by ZaradarBH**
Enabled OAuth (AzureADBearer) middleware support in Capability service.

Cleaned up our utilization of docker so we can now use docker-compose directly from visual studio and via a terminal on linux AND windows!!! :)

Added an .editorconfig which will be picked up automatically by VS Code, Rider and VS. Read more about it @ https://www.jetbrains.com/help/rider/Using_EditorConfig.html

### CODE REVIEW

**Comment by kim-lindhard-dfds** [comment]
Looking at the files in the pull request I count 5 different topics worthy of their own pull request:
1. Reorganize of docker compose.
1. Add editorconfig
1. Rewrite Dockerfile to build the CapabilityService.WebApi project
1. Add authentication
1. Move CapabilityService solution file.

I feel it is hard to give each of these topics the love and scrutiny they deserve in a single pull request. I suggest we charry pick each one into a separate branch and do a pull request on each of them.

**Comment by ZaradarBH** [comment]
> Looking at the files in the pull request I count 5 different topics worthy of their own pull request:
> 
> 1. Reorganize of docker compose.
> 2. Add editorconfig
> 3. Rewrite Dockerfile to build the CapabilityService.WebApi project
> 4. Add authentication
> 5. Move CapabilityService solution file.
> 
> I feel it is hard to give each of these topics the love and scrutiny they deserve in a single pull request. I suggest we charry pick each one into a separate branch and do a pull request on each of them.

Yeah... not going to happen. We have alot of clean up to do and if I have to make PRs for each little part it will take forever to get done and quiet frankly it would bring us dangerously close to having a PR per commit.

**Comment by kim-lindhard-dfds** [comment]
> > Looking at the files in the pull request I count 5 different topics worthy of their own pull request:
> > 
> > 1. Reorganize of docker compose.
> > 2. Add editorconfig
> > 3. Rewrite Dockerfile to build the CapabilityService.WebApi project
> > 4. Add authentication
> > 5. Move CapabilityService solution file.
> > 
> > I feel it is hard to give each of these topics the love and scrutiny they deserve in a single pull request. I suggest we charry pick each one into a separate branch and do a pull request on each of them.
> 
> Yeah... not going to happen. We have alot of clean up to do and if I have to make PRs for each little part it will take forever to get done and quiet frankly it would bring us dangerously close to having a PR per commit.

I disagree, as I see it the review of your current PR will take longer time and be more risk prone than splitting the concerns into different pull requests.

**Comment by janwiberg-dfds** [comment]
From a “feature” perspective, there seems to be two things in play here: 

1. a relatively large rework of the local development flow which will require learning/training/flow changes for other developers on the project
2. a new feature

At first look, it seems the “commit slicing” is great. OTOH, there is no direct correlation between “internal feature 1”  and “external feature 2”. Obviously, there is a balance to be considered between expediency and modularity here. I’d lean towards splitting this into two PRs, and making sure that everybody else is caught up on the ramifications of the rework (if relevant. I’m on an iPad today so can’t try it out).

**Comment by ZaradarBH** [comment]
> From a “feature” perspective, there seems to be two things in play here:
> 
> 1. a relatively large rework of the local development flow which will require learning/training/flow changes for other developers on the project
> 2. a new feature
> 
> At first look, it seems the “commit slicing” is great. OTOH, there is no direct correlation between “internal feature 1” and “external feature 2”. Obviously, there is a balance to be considered between expediency and modularity here. I’d lean towards splitting this into two PRs, and making sure that everybody else is caught up on the ramifications of the rework (if relevant. I’m on an iPad today so can’t try it out).

Its a non-intrusive update of our docker files and artifacts. It will have zero impact on anything in the existing developer setup, but will enable those of us on Windows to actually work with the solution (which we couldnt before). So if you take the time to actually look into what is happening you will realize that the ONLY significant change here is #4 (and maybe #2 if you want to be nitty-gritty) and thus making more then 1 PR seems like an epic waste of time.  The other changes could have been avoided if we had some simple engineering guidelines in place and/or just configured GitHub to handle line endings @ https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings

**Pull request closed without merging**
