### PR TITLE
Liveness is only when starting and readiness is for the full lifetime…

### PR DESCRIPTION
**Pull request by wcarlsen**
… (Kubernetes stupid naming convention)

### CODE REVIEW

**Comment by janwiberg-dfds** [comment]
@wcarlsen Not to be a mega-nerd about it,</lie> but liveness vs readiness is not related to the lifecycle. It's related to whether the app is alive/stuck/deadlocked vs momentarily overloaded/busy with something else but is expected to resume.

**Comment by wcarlsen** [comment]
You are misunderstanding my comment. I'm talking not talking about the pods, but when the probes are relevant/active during the a pods lifetime.

**Comment by kim-lindhard-dfds** [comment]
@wcarlsen Did you land this one with jan?

**Comment by wcarlsen** [comment]
@kim-lindhard-dfds Yeah we did discuss it, and it turns out that the Kubernetes official documentation is a bit misleading with the note shown in the picture 
image. We have still not landed weather or not it should be two separate endpoints for the two probes. Right now they share the same.

**Review by kim-lindhard-dfds — APPROVED** [review]

**Pull request merged**
