### PR TITLE
Update .vsts-ci.yml for Azure Pipelines

### PR DESCRIPTION
**Pull request by kim-lindhard-dfds**

### CODE REVIEW

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |0|
| **Quality Gates** |OK|
| **Description** |Defaulting to Low Risk since all modified content is filtered away. This is either due to excluded content in your CodeScene settings, or because the change set only contains renames.|

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |10|
| **Quality Gates** |OK|
| **Description** |The risk increases as the author has somewhat lower experience in this repository.|
| **Warnings** |Delta Analysis Info<br/><ul><li>1 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamemd. Skipping code health checks for those files.</li></ul>|

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |10|
| **Quality Gates** |OK|
| **Description** |The risk increases as the author has somewhat lower experience in this repository.|
| **Warnings** |Delta Analysis Info<br/><ul><li>1 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamemd. Skipping code health checks for those files.</li></ul>|

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |10|
| **Quality Gates** |OK|
| **Description** |The risk increases as the author has somewhat lower experience in this repository.|
| **Warnings** |Delta Analysis Info<br/><ul><li>1 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamemd. Skipping code health checks for those files.</li></ul>|

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |10|
| **Quality Gates** |OK|
| **Description** |The risk increases as the author has somewhat lower experience in this repository.|
| **Warnings** |Delta Analysis Info<br/><ul><li>1 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamemd. Skipping code health checks for those files.</li></ul>|

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |10|
| **Quality Gates** |OK|
| **Description** |The risk increases as the author has somewhat lower experience in this repository.|
| **Warnings** |Delta Analysis Info<br/><ul><li>1 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamemd. Skipping code health checks for those files.</li></ul>|

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |10|
| **Quality Gates** |OK|
| **Description** |The risk increases as the author has somewhat lower experience in this repository.|
| **Warnings** |Delta Analysis Info<br/><ul><li>1 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamemd. Skipping code health checks for those files.</li></ul>|

**Review by HenrikStanley — APPROVED** [review]
Looks good, we have changed the filename to conform to the new naming standard for ADO yaml files.
Rest of the pipeline has also been readied for CI / CD in one file at a later date.

**Pull request merged**
